const { VITE_AUTH_SERVICE_URL, VITE_BOOKING_SERVICE_URL, VITE_INVENTORY_SERVICE_URL, VITE_BILLING_SERVICE_URL } =
  import.meta.env;

const API_URLS = {
  AUTH: VITE_AUTH_SERVICE_URL,
  BOOKING: VITE_BOOKING_SERVICE_URL,
  INVENTORY: VITE_INVENTORY_SERVICE_URL,
  BILLING: VITE_BILLING_SERVICE_URL,
};

export default API_URLS;